travis:
  secure:
    BINSTAR_TOKEN: awqYPvRN7Q4sdfUpEz/wCYvV5PT5k7y29M1QWOxo3xBdsMr/9RxlW6x2Xt4oALWqUDTvctsLKzGZJ2VKBgrAG3iFX/lBVHr+jo0xXHRIE0XK1tDLb26jhuV9lzmAuhWtURPPLAmXh2UZHVeE1dJtGDUmti9kvESxrYpBr9Dm4cbJvFNtAnB7nixDgBopE7dz093NH847fk1BEh9tUO4jf7loAhoD/XiwIZ4qj1DM0kk3A9My2cQnxHRHnlqbZ9l1a80VJhuuRuwqNw6RK3rIfVP7n7pXcVHXAjj01kHchi2SYOny7I8oZJTD041rZy7m1gR2EeMb738Di7koWnxamTNb5EryRiJ+xG78FFaanl9UpBQVWuo6NXoly/FG/OxTvm0RZ2bXvrJER6pDWqxS8m0N9Epw7nGJOz7iZGzeB4pytigOdUEhuxHvL+QUmEQiwsEODYLqoZe20vTuR/ZImdLDm9V9nCXqNuq3V8ulkhPduEyELHuuweBNdaDPJXGh74khdhD6MgvMyzwge65g//8YUGcgI9samX+coiRHOoZ4rS+PZjBUwVtSwxAav0eFChLwFpwP9NO+vqa9yAh+Af7HlCmpzXi8mjzRqn9cn3LixLQVj5y6mApWkYO1d5GQrs+Vn6Ck9zPlmzsvxZ4oYaqKPawLKix149b2QzpENuo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
